### ISSUE TITLE
Warning en la generación aleatoria de revisores

### ISSUE THREAD

**Issue by amerigal** [JJ/IV-21-22#314]
Cuando se generan revisores aleatorios para un objetivo que han completado menos de tres personas se produce un error como el siguiente:

```
Use of uninitialized value $this_reviewer in concatenation (.) or string at t/random-reviewer line 9259.
Use of uninitialized value $this_reviewer in concatenation (.) or string at t/random-reviewer line 9259.
::warning::⛹ Revisores → @Slowmybrosh @ @
```

**Comment by JJ** [comment]
Es nada más que un warning, en realidad, y forma parte del MVP :-) Pero tienes razón, no queda bien.

**Comment by amerigal** [comment]
Bueno es verdad, tampoco tiene mucha importancia, pero por si aporta un poco.
